# Generated by Django 6.0 on 2025-12-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.URLField(blank=True, help_text='URL de la imagen del avatar', max_length=500, null=True),
        ),
    ]
