# Generated by Django 6.0 on 2026-01-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['muscle_group', 'exercise_type', 'name']},
        ),
    ]
