# Generated by Django 6.0 on 2026-01-07 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='created_by',
            new_name='user',
        ),
    ]
